default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['SPA_PRACTICE_DB_USER'] %>
  password: <%= ENV['SPA_PRACTICE_DB_USER_PASSWORD'] %>
  host: <%= ENV['SPA_PRACTICE_DB_HOST'] %>
  database: <%= ENV['SPA_PRACTICE_DB_NAME'] %>

development:
  <<: *default

test:
  <<: *default
#
production:
  <<: *default
